"""initial schema

Revision ID: 8dab12dd6727
Revises:
Create Date: 2026-07-14 16:03:43.971452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dab12dd6727'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name=op.f('fk_categories_parent_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name='uq_categories_name'),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_interval IN ('monthly', 'yearly')", name=op.f('ck_subscription_plans_billing_interval_valid')),
    sa.CheckConstraint("target_role IN ('customer', 'artist')", name=op.f('ck_subscription_plans_target_role_valid')),
    sa.CheckConstraint('price_amount >= 0', name=op.f('ck_subscription_plans_price_amount_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('name', name='uq_subscription_plans_name'),
    sa.UniqueConstraint('slug', name='uq_subscription_plans_slug')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name='uq_tags_name'),
    sa.UniqueConstraint('slug', name='uq_tags_slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('customer', 'artist', 'moderator', 'administrator', 'super_administrator')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deactivated')", name=op.f('ck_users_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('ai_generations',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_session_id', sa.String(length=100), nullable=True),
    sa.Column('generation_type', sa.String(length=30), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("generation_type IN ('design_discovery', 'photo_preview', 'generative_design')", name=op.f('ck_ai_generations_generation_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name=op.f('ck_ai_generations_status_valid')),
    sa.CheckConstraint('cost_usd IS NULL OR cost_usd >= 0', name=op.f('ck_ai_generations_cost_usd_non_negative')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_ai_generations_latency_ms_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_generations_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generations'))
    )
    op.create_index(op.f('ix_ai_generations_user_id'), 'ai_generations', ['user_id'], unique=False)
    op.create_table('artist_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.SmallInteger(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_accepting_bookings', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("verification_status IN ('pending', 'under_review', 'verified', 'rejected', 'suspended')", name=op.f('ck_artist_profiles_verification_status_valid')),
    sa.CheckConstraint('rating_average >= 0 AND rating_average <= 5', name=op.f('ck_artist_profiles_rating_average_range')),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_artist_profiles_rating_count_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artist_profiles_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_artist_profiles_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_profiles')),
    sa.UniqueConstraint('user_id', name='uq_artist_profiles_user_id')
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('collections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('user_id', 'name', name='uq_collections_user_name')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('coupons',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('min_booking_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("discount_type IN ('percentage', 'fixed_amount')", name=op.f('ck_coupons_discount_type_valid')),
    sa.CheckConstraint('discount_value > 0', name=op.f('ck_coupons_discount_value_positive')),
    sa.CheckConstraint('max_redemptions IS NULL OR max_redemptions > 0', name=op.f('ck_coupons_max_redemptions_positive')),
    sa.CheckConstraint('redemption_count >= 0', name=op.f('ck_coupons_redemption_count_non_negative')),
    sa.CheckConstraint('valid_until IS NULL OR valid_until > valid_from', name=op.f('ck_coupons_valid_until_after_valid_from')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_coupons_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name='uq_coupons_code')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('push', 'email', 'sms', 'in_app')", name=op.f('ck_notifications_channel_valid')),
    sa.CheckConstraint("type IN ('booking_update', 'message', 'verification', 'payment', 'system', 'marketing')", name=op.f('ck_notifications_type_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name='uq_profiles_user_id')
    )
    op.create_table('reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_entity_type', sa.String(length=30), nullable=False),
    sa.Column('reported_entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reported_entity_type IN ('design', 'comment', 'message', 'user', 'artist_profile', 'review')", name=op.f('ck_reports_entity_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'reviewing', 'resolved', 'dismissed')", name=op.f('ck_reports_status_valid')),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_reports_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'expired', 'past_due', 'trialing')", name=op.f('ck_subscriptions_status_valid')),
    sa.CheckConstraint('current_period_end > current_period_start', name=op.f('ck_subscriptions_period_end_after_start')),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('provider_subscription_id', name='uq_subscriptions_provider_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name='uq_system_settings_key')
    )
    op.create_table('user_devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('ios', 'android', 'web')", name=op.f('ck_user_devices_platform_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_devices')),
    sa.UniqueConstraint('device_token', name='uq_user_devices_device_token')
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_table('artist_availability',
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name=op.f('ck_artist_availability_day_of_week_range')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_artist_availability_end_time_after_start_time')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_artist_availability_artist_profile_id_artist_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_availability')),
    sa.UniqueConstraint('artist_profile_id', 'day_of_week', 'start_time', 'end_time', name='uq_artist_availability_slot')
    )
    op.create_index(op.f('ix_artist_availability_artist_profile_id'), 'artist_availability', ['artist_profile_id'], unique=False)
    op.create_table('artist_blocked_dates',
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_artist_blocked_dates_end_date_gte_start_date')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_artist_blocked_dates_artist_profile_id_artist_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_blocked_dates'))
    )
    op.create_index(op.f('ix_artist_blocked_dates_artist_profile_id'), 'artist_blocked_dates', ['artist_profile_id'], unique=False)
    op.create_table('artist_documents',
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('id_proof', 'business_license', 'portfolio_sample', 'other')", name=op.f('ck_artist_documents_document_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_artist_documents_status_valid')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_artist_documents_artist_profile_id_artist_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_artist_documents_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_documents'))
    )
    op.create_index(op.f('ix_artist_documents_artist_profile_id'), 'artist_documents', ['artist_profile_id'], unique=False)
    op.create_table('artist_services',
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("pricing_type IN ('fixed', 'range', 'custom_quote')", name=op.f('ck_artist_services_pricing_type_valid')),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name=op.f('ck_artist_services_duration_positive')),
    sa.CheckConstraint('price_amount IS NULL OR price_amount >= 0', name=op.f('ck_artist_services_price_amount_non_negative')),
    sa.CheckConstraint('price_max IS NULL OR price_min IS NULL OR price_max >= price_min', name=op.f('ck_artist_services_price_max_gte_price_min')),
    sa.CheckConstraint('price_min IS NULL OR price_min >= 0', name=op.f('ck_artist_services_price_min_non_negative')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_artist_services_artist_profile_id_artist_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_services'))
    )
    op.create_index(op.f('ix_artist_services_artist_profile_id'), 'artist_services', ['artist_profile_id'], unique=False)
    op.create_table('designs',
    sa.Column('artist_profile_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('body_placement', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("body_placement IN ('hand', 'foot', 'arm', 'back', 'other')", name=op.f('ck_designs_body_placement_valid')),
    sa.CheckConstraint("difficulty_level IN ('beginner', 'intermediate', 'advanced')", name=op.f('ck_designs_difficulty_level_valid')),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived', 'flagged')", name=op.f('ck_designs_status_valid')),
    sa.CheckConstraint('like_count >= 0', name=op.f('ck_designs_like_count_non_negative')),
    sa.CheckConstraint('view_count >= 0', name=op.f('ck_designs_view_count_non_negative')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_designs_artist_profile_id_artist_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designs'))
    )
    op.create_index(op.f('ix_designs_artist_profile_id'), 'designs', ['artist_profile_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('follower_user_id', sa.UUID(), nullable=False),
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_follows_artist_profile_id_artist_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], name=op.f('fk_follows_follower_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('follower_user_id', 'artist_profile_id', name='uq_follows_follower_artist')
    )
    op.create_index(op.f('ix_follows_artist_profile_id'), 'follows', ['artist_profile_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_user_id'), 'follows', ['follower_user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('design_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time', sa.Time(), nullable=True),
    sa.Column('location_type', sa.String(length=30), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("location_type IN ('customer_location', 'artist_studio', 'other')", name=op.f('ck_bookings_location_type_valid')),
    sa.CheckConstraint("status IN ('requested', 'quoted', 'confirmed', 'completed', 'cancelled', 'disputed', 'declined', 'expired')", name=op.f('ck_bookings_status_valid')),
    sa.CheckConstraint('deposit_amount IS NULL OR deposit_amount >= 0', name=op.f('ck_bookings_deposit_amount_non_negative')),
    sa.CheckConstraint('total_amount IS NULL OR total_amount >= 0', name=op.f('ck_bookings_total_amount_non_negative')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_bookings_artist_profile_id_artist_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], name=op.f('fk_bookings_cancelled_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_bookings_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_bookings_design_id_designs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['artist_services.id'], name=op.f('fk_bookings_service_id_artist_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_artist_profile_id'), 'bookings', ['artist_profile_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_collection_items_design_id_designs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items')),
    sa.UniqueConstraint('collection_id', 'design_id', name='uq_collection_items_collection_design')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_design_id'), 'collection_items', ['design_id'], unique=False)
    op.create_table('comments',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_comments_design_id_designs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('fk_comments_parent_comment_id_comments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index(op.f('ix_comments_design_id'), 'comments', ['design_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('design_categories',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_design_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_design_categories_design_id_designs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('design_id', 'category_id', name=op.f('pk_design_categories'))
    )
    op.create_table('design_images',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_design_images_design_id_designs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design_images')),
    sa.UniqueConstraint('design_id', 'sort_order', name='uq_design_images_sort_order')
    )
    op.create_index(op.f('ix_design_images_design_id'), 'design_images', ['design_id'], unique=False)
    op.create_table('design_tags',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_design_tags_design_id_designs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_design_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('design_id', 'tag_id', name=op.f('pk_design_tags'))
    )
    op.create_table('likes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_likes_design_id_designs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_likes')),
    sa.UniqueConstraint('user_id', 'design_id', name='uq_likes_user_design')
    )
    op.create_index(op.f('ix_likes_design_id'), 'likes', ['design_id'], unique=False)
    op.create_index(op.f('ix_likes_user_id'), 'likes', ['user_id'], unique=False)
    op.create_table('preview_projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=True),
    sa.Column('source_image_url', sa.String(length=2048), nullable=False),
    sa.Column('result_image_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('ck_preview_projects_status_valid')),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_preview_projects_design_id_designs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preview_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preview_projects'))
    )
    op.create_index(op.f('ix_preview_projects_user_id'), 'preview_projects', ['user_id'], unique=False)
    op.create_table('booking_attachments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=2048), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("file_type IN ('image', 'document', 'other')", name=op.f('ck_booking_attachments_file_type_valid')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_attachments_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_booking_attachments_uploaded_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_attachments'))
    )
    op.create_index(op.f('ix_booking_attachments_booking_id'), 'booking_attachments', ['booking_id'], unique=False)
    op.create_table('booking_quotes',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'expired', 'superseded')", name=op.f('ck_booking_quotes_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_booking_quotes_amount_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_quotes_booking_id_bookings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_quotes'))
    )
    op.create_index(op.f('ix_booking_quotes_booking_id'), 'booking_quotes', ['booking_id'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('requested', 'quoted', 'confirmed', 'completed', 'cancelled', 'disputed', 'declined', 'expired')", name=op.f('ck_booking_status_history_from_status_valid')),
    sa.CheckConstraint("to_status IN ('requested', 'quoted', 'confirmed', 'completed', 'cancelled', 'disputed', 'declined', 'expired')", name=op.f('ck_booking_status_history_to_status_valid')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_status_history_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_booking_status_history_changed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_status_history'))
    )
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_table('conversations',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('booking', 'inquiry', 'support')", name=op.f('ck_conversations_type_valid')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_conversations_booking_id_bookings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_booking_id'), 'conversations', ['booking_id'], unique=False)
    op.create_table('coupon_redemptions',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('discount_applied > 0', name=op.f('ck_coupon_redemptions_discount_applied_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_coupon_redemptions_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_redemptions_coupon_id_coupons'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_coupon_redemptions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_redemptions')),
    sa.UniqueConstraint('coupon_id', 'user_id', name='uq_coupon_redemptions_coupon_user')
    )
    op.create_index(op.f('ix_coupon_redemptions_coupon_id'), 'coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_coupon_redemptions_user_id'), 'coupon_redemptions', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_type IN ('deposit', 'balance', 'full')", name=op.f('ck_payments_payment_type_valid')),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed', 'refunded', 'partially_refunded')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name=op.f('fk_payments_payer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('provider_payment_id', name='uq_payments_provider_payment_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payouts',
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_payout_id', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'paid', 'failed')", name=op.f('ck_payouts_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payouts_amount_positive')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_payouts_artist_profile_id_artist_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payouts_booking_id_bookings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index(op.f('ix_payouts_artist_profile_id'), 'payouts', ['artist_profile_id'], unique=False)
    op.create_table('reviews',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('artist_profile_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('artist_response', sa.Text(), nullable=True),
    sa.Column('artist_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['artist_profile_id'], ['artist_profiles.id'], name=op.f('fk_reviews_artist_profile_id_artist_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_reviews_customer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('booking_id', name='uq_reviews_booking_id')
    )
    op.create_index(op.f('ix_reviews_artist_profile_id'), 'reviews', ['artist_profile_id'], unique=False)
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('customer', 'artist', 'moderator', 'admin')", name=op.f('ck_conversation_members_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_members_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_members')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_members_conv_user')
    )
    op.create_index(op.f('ix_conversation_members_conversation_id'), 'conversation_members', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_members_user_id'), 'conversation_members', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=2048), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("message_type IN ('text', 'image', 'system')", name=op.f('ck_messages_message_type_valid')),
    sa.CheckConstraint('body IS NOT NULL OR attachment_url IS NOT NULL', name=op.f('ck_messages_body_or_attachment_present')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('provider_refund_id', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'processed', 'rejected')", name=op.f('ck_refunds_status_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_refunds_processed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_members_user_id'), table_name='conversation_members')
    op.drop_index(op.f('ix_conversation_members_conversation_id'), table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_artist_profile_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payouts_artist_profile_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_coupon_redemptions_user_id'), table_name='coupon_redemptions')
    op.drop_index(op.f('ix_coupon_redemptions_coupon_id'), table_name='coupon_redemptions')
    op.drop_table('coupon_redemptions')
    op.drop_index(op.f('ix_conversations_booking_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_booking_quotes_booking_id'), table_name='booking_quotes')
    op.drop_table('booking_quotes')
    op.drop_index(op.f('ix_booking_attachments_booking_id'), table_name='booking_attachments')
    op.drop_table('booking_attachments')
    op.drop_index(op.f('ix_preview_projects_user_id'), table_name='preview_projects')
    op.drop_table('preview_projects')
    op.drop_index(op.f('ix_likes_user_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_design_id'), table_name='likes')
    op.drop_table('likes')
    op.drop_table('design_tags')
    op.drop_index(op.f('ix_design_images_design_id'), table_name='design_images')
    op.drop_table('design_images')
    op.drop_table('design_categories')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_design_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_collection_items_design_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_artist_profile_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_follows_follower_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_artist_profile_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_designs_artist_profile_id'), table_name='designs')
    op.drop_table('designs')
    op.drop_index(op.f('ix_artist_services_artist_profile_id'), table_name='artist_services')
    op.drop_table('artist_services')
    op.drop_index(op.f('ix_artist_documents_artist_profile_id'), table_name='artist_documents')
    op.drop_table('artist_documents')
    op.drop_index(op.f('ix_artist_blocked_dates_artist_profile_id'), table_name='artist_blocked_dates')
    op.drop_table('artist_blocked_dates')
    op.drop_index(op.f('ix_artist_availability_artist_profile_id'), table_name='artist_availability')
    op.drop_table('artist_availability')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('artist_profiles')
    op.drop_index(op.f('ix_ai_generations_user_id'), table_name='ai_generations')
    op.drop_table('ai_generations')
    op.drop_index('uq_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('subscription_plans')
    op.drop_table('categories')
    # ### end Alembic commands ###
